source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ElloCerts_Example' do
  pod 'ElloOSSCerts', :path => '../'
end

target 'ElloCerts_Tests' do
  pod 'ElloOSSCerts', :path => '../'

  pod 'Quick', '~> 0.9'
  pod 'Nimble', '~> 4.0'
end
