source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ElloCerts_Example' do
  pod 'ElloOSSCerts', :path => '../'
end

target 'ElloCerts_Tests' do
  pod 'ElloOSSCerts', :path => '../'

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.0'
end
